# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Gustavo Penha
paginate:       5
# baseurl:        "/guzblog"
# url:            "https://guzpenha.github.io/guzblog"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Gustavo Penha
  url:          https://about.me/gustavopenha
  email:        guzpenha10@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
